# Generated by Django 4.0.2 on 2022-03-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Notice',
            new_name='notice',
        ),
    ]
